### ISSUE TITLE
Make "precompile" do the right thing on older Julia versions

### ISSUE THREAD

**Issue by thomasjm** [codedownio/julia2nix#1]

**Comment by colinxs** [comment]
Somewhat related, does it even make sense to include the precompile cache in the derivation? AFAIK those files are platform dependent and contain embedded absolute paths and system details.

**Comment by thomasjm** [comment]
I think so...it speeds up the first use of the package. Platform dependency shouldn't be an issue because Nix already segregates its derivations by platform I think (doesn't the platform appear in the derivation somewhere and get hashed along with it?) If you can show me an example of an undesirable embedded path or system detail we can look at it--I tend to think of those as problems to be solved on the Julia side. In any case Julia is pretty conservative about using precompiled files, if they smell wrong to Julia (via timestamps etc.) it tends to ignore them.

**Comment by colinxs** [comment]
One thing that occurs is that all the generated .ji files contain absolute
paths to the build environment.

This is a similar problem to embedded paths in binaries or shebangs but we
have tools like autopatchelf for those (I did write a script to patch those
paths but figured it wasn't worth the effort, especially with parallel
precompilation in Julia > 1.6).

If you're curious go open up some of the .ji files after building and
you'll see those paths.

**Comment by thomasjm** [comment]
I'm going to close this, and consider support dropped for those older Julia versions as far as the precompile issue. Feel free to open a new issue if there's still a problem with the runtime closure being too big.
