### ISSUE TITLE
Does anyone solved the GR Build with Julia2nix?

### ISSUE THREAD

**Issue by GTrunSec** [codedownio/julia2nix#11]
Thanks, any idea here or patch:
![image](https://user-images.githubusercontent.com/21156405/110063114-6365b480-7d1f-11eb-896f-a815660d642a.png)

Test with https://github.com/GTrunSec/my-julia2nix-env/blob/main/shell.nix
I did a [patch](https://github.com/GTrunSec/Jupyter-data-science-environment/blob/master/my-default.nix#L82) to solve it without nix-store in Jupyter IJulia. So, just a discussion here.

**Comment by thomasjm** [comment]
Solving GR is the only entry in the wiki right now :)

https://github.com/thomasjm/julia2nix/wiki#grjl

**Comment by GTrunSec** [comment]
Thanks for your wiki.
please, let this issue still open while my [shell](https://github.com/GTrunSec/my-julia2nix-env/blob/main/shell.nix) testing to julia2nix.

**Comment by GTrunSec** [comment]
Done to integrated into [Jupyter kernel.](https://github.com/GTrunSec/Jupyter-data-science-environment/blob/4020c69b830d9c8e8214c43f1afc4c95b152e100/my-default.nix#L63)

**Comment by GTrunSec** [comment]
Snappy
```
  Building Snappy ───→ `/nix/store/pz9db61cf40qzvjlwxzhkm49dpmnnnra-julia-depot/packages/Snappy/O2CHr/deps/build.log`   
┌ Error: Error building `Snappy`:                                                                                        
│ [ Info: Directory /nix/store/pz9db61cf40qzvjlwxzhkm49dpmnnnra-julia-depot/packages/Snappy/O2CHr/deps/usr/lib does not e
xist!                                                                                                                    
│ ┌ Warning: Could not extract the platform key of https://github.com/davidanthoff/SnappyBuilder/releases/download/v1.1.7
%2Bbuild.1/SnappyBuilder.x86_64-linux-gnu.tar.gz; continuing...                                                          
│ └ @ BinaryProvider /nix/store/pz9db61cf40qzvjlwxzhkm49dpmnnnra-julia-depot/packages/BinaryProvider/U2dKK/src/Prefix.jl:
185                                                                                                                      
│ [ Info: Downloading https://github.com/davidanthoff/SnappyBuilder/releases/download/v1.1.7%2Bbuild.1/SnappyBuilder.x86_
64-linux-gnu.tar.gz to /nix/store/pz9db61cf40qzvjlwxzhkm49dpmnnnra-julia-depot/packages/Snappy/O2CHr/deps/usr/downloads/S
nappyBuilder.x86_64-linux-gnu.tar.gz...                                                                                  
│ ERROR: LoadError: Could not download https://github.com/davidanthoff/SnappyBuilder/releases/download/v1.1.7%2Bbuild.1/S
nappyBuilder.x86_64-linux-gnu.tar.gz to /nix/store/pz9db61cf40qzvjlwxzhkm49dpmnnnra-julia-depot/packages/Snappy/O2CHr/dep
s/usr/downloads/SnappyBuilder.x86_64-linux-gnu.tar.gz:                                                                   
│ ErrorException("")                                                                                                     
│ Stacktrace:                                                      
```

**Comment by thomasjm** [comment]
Yeah, it looks like a similar suggestion as for GR.jl. For example, Snappy looks like it will try to download `libsnappy` if it doesn't find it: https://github.com/bicycle1885/Snappy.jl/blob/master/deps/build.jl.

On the bright side, a similar fix should work (put `libsnappy` in the `extraLibs` section).

Would you be interested in contributing fixes for these packages to the wiki?

**Comment by GTrunSec** [comment]
Do you know how to fix this issue as following?

```
tarball 'https://github.com/davidanthoff/SnappyBuilder/releases/download/v1.1.7%2Bbuild.2/Snappy.x86_64-linux-gnu.tar.gz' contains an unexpected number of top-level files
(use '--show-trace' to show detailed location information)
```

**Comment by GTrunSec** [comment]
unworking-path, any idea here? thanks
```
{ pkgs ? import <nixpkgs> { } }:
with pkgs;
let
  src = fetchurl {
    url = "https://github.com/davidanthoff/SnappyBuilder/releases/download/v1.1.7%2Bbuild.2/Snappy.x86_64-linux-gnu.tar.gz";
    sha256 = "sha256-4xvDcStCDLG5kdCFeXP0U9IAR5k5UhRvjvl4qank0sg=";
  };

in
runCommand "libsnappy-1.7.0" { inherit src; } ''
  tar -xf $src .
  mkdir -p $out
  cp -r include $out/.
  cp -r lib $out/.
''

```

**Comment by thomasjm** [comment]
Oh I'd just use the `snappy` in Nixpkgs. Does it work to just put `extraLibs = [snappy];` in `default.nix`?

**Comment by GTrunSec** [comment]
> Oh I'd just use the `snappy` in Nixpkgs. Does it work to just put `extraLibs = [snappy];` in `default.nix`?

it does not work. 
```
│ [ Info: Directory /nix/store/2kifk7k58kxjqkz0a60qm87z1garsz56-julia-depot/packages/Snappy/O2CHr/deps/usr/lib does not e
xist!                                 
```
looks link need to link the ${libsnappy}/lib to depo/Snappy/*/usr/lib?

**Comment by thomasjm** [comment]
I think you just need to convince [BinaryProvider.jl](https://github.com/JuliaPackaging/BinaryProvider.jl) to find the library. I was hoping that putting it on LD_LIBRARY_PATH would be enough. 

Oh, are you on a Mac by any chance? In that case it would need to be `DYLD_LIBRARY_PATH`. This library doesn't distinguish by platform yet but you could try it manually.

**Comment by GTrunSec** [comment]
I did a [dirty hack ](https://github.com/GTrunSec/my-julia2nix-env/blob/5b8a5aa1e08557bc499aeb61d3c143b16b0021ef/default.nix#L62)to fix that.

**Comment by thomasjm** [comment]
GR works fine in recent versions, and is tested in CI now.
