### ISSUE TITLE
Include overrides file in julia2nix

### ISSUE THREAD

**Issue by jtrakk** [codedownio/julia2nix#2]
https://github.com/nix-community/poetry2nix includes a default [`overrides.nix` file](https://github.com/nix-community/poetry2nix/blob/master/overrides.nix) instead of a wiki, so the overrides work by default.

**Comment by thomasjm** [comment]
Now that the artifacts situation is much better in Julia, we don't need the wiki anymore as far as I can tell. Going to close this also.
