### ISSUE TITLE
Removing fetchgit

### ISSUE THREAD

**Issue by johnrichardrinehart** [codedownio/julia2nix#24]
The README stipulates that the `fetchgit` folder is necessary until [this PR lands](https://github.com/NixOS/nixpkgs/pull/104714). It's landed. Can we remove `fetchgit`, now?

**Comment by thomasjm** [comment]
Well, the PR is reflected in Nixpkgs release 21.05. So if you're running against that or later then you can certainly remove the `fetchgit` folder and make the corresponding change to `common.nix`.

As far as modifying `julia2nix` to not produce it as the default behavior, I'm not sure if a sizeable number of people are still running against older versions? Seems like we probably want to stop creating `fetchgit` by default but provide a flag so people on older Nixpkgs can still do it.

**Comment by johnrichardrinehart** [comment]
Sorry for the late response. I think as it's almost time for the next `nix` release it's safe to assume that the majority of users will be on `21.05` or later (`unstable`). I think the flag to stop creating `fetchgit` by default would be the best thing to do, in that case, adding some documentation to the `README` to help those using older `nixpkgs`.

I have a note on my to-do list to PR this repo with that flag. It may end up being one of those things that I never get around to, though.  Please wait 2 weeks if you want this implemented, to give me a chance to try to help out.

Thanks!

**Comment by thomasjm** [comment]
`fetchgit` is gone now!
