### ISSUE TITLE
Register in nixpkgs

### ISSUE THREAD

**Issue by schlichtanders** [codedownio/julia2nix#25]
Hi, it would be great to have julia2nix available in nixos and nixpkgs.

**Comment by thomasjm** [comment]
I actually have a master plan to put all Julia packages in Nixpkgs, so you won't need `julia2nix`.

If anyone urgently desires `julia2nix` in Nixpkgs in the meantime, feel free to make a PR there. Personally I'll only do so if/when the master plan doesn't end up working out.

**Comment by schlichtanders** [comment]
thank you for the update.
to have all jupyter packages in nix is awesome, but I would see this complementary.

All julia users and developers know how to write Project.toml files. Also when I am developing Julia, I am developing using Julia Project.toml because it is the Julia standard. I am not tracking dependencies in nix.

Nevertheless it would be great to instantiate a nix-shell with all dependencies.
My personal ideal would be to have a requirements.txt for python, Project.toml for Julia, etc. and then be able to create a nix project for it (nix-shell and/or flake).

**Comment by thomasjm** [comment]
Hmm okay, fair enough. In that case maybe we add it to Nixpkgs sooner.

Let's still hold off until one more problem is solved -- I want to figure out how to do a better job of ensuring that the generated Nix uses the same Julia that the `Project.toml`/`Manifest.toml` came from. (It's kind of tricky for older Julias but manifest format 2.0 has a field for it...)

**Comment by thomasjm** [comment]
Julia package support has landed in Nixpkgs so I'll close this now
