### ISSUE TITLE
Providing julia2nix library instead of generating files

### ISSUE THREAD

**Issue by jtrakk** [codedownio/julia2nix#3]
poetry2nix doesn't generate files in the user's directory. It provides a library that the user can import and use. I like that this is cleaner and doesn't require committing generated code.

**Comment by jtrakk** [comment]
The basic idea: User provides a Registry revision, a Project.toml, and a Manifest.toml. Download the registry into the nix store (fixed-output). For each package, find the appropriate repo in the registry. Construct the github url of the package commit. Create a fixed-output derivation using the hash from the manifest.

**Comment by thomasjm** [comment]
> Create a fixed-output derivation using the hash from the manifest.

I think the question is, given a git tree hash (which is a SHA1), can we compute the `outputHash` needed by the FOD? You can set `outputHashAlgo = "sha1"` but I'm not sure if the hashes are going to be computed the same way. (I think git tree hashes are a hash of the git object representing a tree of files...)

**Comment by aaronjanse** [comment]
An alternative could doing this (roughly) like Cargo, where all libraries are downloaded first then hashed all together (with a single hash). We could then put them back in their original place. Sounds like a lot of work, though.

In the meantime, thank you @thomasjm for writing this. It's going to save me _a lot_ of time while playing with Julia on NixOS.

**Comment by thomasjm** [comment]
I'm going to close this for the same reason as #18. The dream will be kept alive as a separate project to add Julia packages to Nixpkgs and/or add git tree hashes as a Nix FOD algorithm mode.
