### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by jtrakk** [codedownio/julia2nix#7]
julia2nix fails in various ways when installing packages. It would be nice to have some reliability assurances, such as automated testing and continuous integration. 

Since the list of packages is available, a list of popular packages can be used for testing.

**Comment by thomasjm** [comment]
Yep, CI would be good -- please keep reporting the failures though so we can keep shaking things out.

**Comment by thomasjm** [comment]
CI is running now. Contributions for tricky packages are welcome in `.github/workflows/ci.yml`
